title: WAF++
url: https://waf2p.dev
baseurl: ""
google_analytics_key: null
google_maps_javascript_api_key: null
disqus_shortname: null
logo: https://avatars.githubusercontent.com/u/245947051
description: WAF++ ist ein community-getriebenes, cloud-agnostisches Open-Source-Framework
  f√ºr Architektur, Security, Governance und Reifegradmodelle.
author:
  name: WAF++ Community
  email: info@wafpp.dev
  twitter: ''
social:
  name: CNC by Vogel IT
  links:
  - https://www.cloudnativeconference.de/
timezone: Etc/UTC

collections:
  staff_members:
    output: false
    _hide_content: false
paginate: 10
paginate_path: /blog/:num/
permalink: pretty
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    _options:
      content:
        width: 1500
        height: 2500
- scope:
    path: ''
    type: staff_members
  values:
    full_width: true
    layout: staff_member
- scope:
    path: /docs
  values:
    layout: docs
    full_width: false
- scope:
    path: ''
  values:
    layout: page
- scope:
    path: index.html
  values:
    layout: default
jekyll-archives:
  enabled:
  - categories
plugins:
- jekyll-archives
- jekyll-sitemap
- jekyll-seo-tag
- jekyll-feed
- jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - AGENTS.md
  - node_modules
  - package.json
  - package-lock.json
  - Taskfile.yml
  - antora-playbook.yml
  - antora-playbook-local.yml
  - docs
  - .cache
  - build

# Keep Antora-generated docs intact
keep_files:
  - docs

# -----------

_select_data:
  social_icons:
  - Facebook
  - Instagram
  - LinkedIn
  - Pinterest
  - Tumblr
  - Twitter
  - YouTube
  - RSS
  - Github
_comments:
  map: Update the map location and display settings.
  latitude: Coordinates for the center marker on the map.
  longitude: Coordinates for the center marker on the map.
  zoom: The zoom level for the map.
  pricing_table: Update the information in the pricing tables.
  highlight: Emphasis the text
  color: The background colour used in the plan name and call to action.
  new_window: Open link in new window
