site:
  title: WAF++ Documentation
  url: https://waf2p.dev
  start_page: wafpp::index.adoc

content:
  sources:
  # Production: Pull from GitHub
  - url: https://github.com/WAF2p/framework.git
    branches: main

antora:
  extensions:
  - require: '@antora/lunr-extension'
    index_latest_only: true
    index_by_heading: true
    languages: [en, de]
    snippet_length: 150

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./supplemental-ui

asciidoc:
  extensions:
    - asciidoctor-kroki
  attributes:
    page-pagination: ''
    source-language: asciidoc@

output:
  clean: true
  dir: ./_site/docs
